// Static TypeScript ambient declarations for the `esto` and `esto/fs` builtin modules.
// Emitted by `esto types` into the user's working directory as `esto.d.ts`.

pub const ESTO_DTS: &str = r#"// esto.d.ts — ambient declarations for the esto scripting runtime.
// Generated by `esto types`. Add to your tsconfig "include" array.
//
// tsconfig.json minimal setup:
//   {
//     "compilerOptions": {
//       "jsx": "react",
//       "jsxFactory": "h",
//       "jsxFragmentFactory": "Fragment",
//       "noEmit": true
//     },
//     "include": ["**/*.op.tsx", "**/*.op.jsx", "esto.d.ts"]
//   }

// Global JSX namespace required for tsconfig jsxFactory: "h"
declare namespace JSX {
  type Element = object;
  interface IntrinsicElements {
    [key: string]: unknown;
  }
  interface ElementChildrenAttribute {
    children: {};
  }
}

declare module "esto" {
  // Opaque node returned by h() — the currency of the JSX tree.
  type EsNode = object;

  // JSX factory (called by transpiler; import and use as pragma).
  export function h(
    type: any,
    props: Record<string, unknown> | null,
    ...children: unknown[]
  ): EsNode;

  // JSX fragment marker — use <> or <Fragment>.
  export declare const Fragment: unique symbol;

  // Context provider — threads a string or object value to descendant leaves.
  // <Context value="..."> or <Context data={obj}> to pass structured data.
  export declare const Context: unique symbol;

  // Unit definition passed to unit().
  interface UnitDef<T extends Record<string, unknown>> {
    /** Stable identity key for an item — used to detect enter/exit. */
    key?: (item: T) => string;
    /** Opaque change-detection value — update fires when this differs. */
    value?: (item: T) => string;
    /** Returns the current observed set of items. */
    observe?: () => T[];
    /** Called when a new item appears. May return a prompt`` or sh`` call. */
    enter?: (item: T) => void;
    /** Called when an item's value changes. */
    update?: (item: T) => void;
    /** Called when an item disappears from the observed set. */
    exit?: (item: T) => void;
  }

  /**
   * Declares a new unit type.
   *
   *   const File = unit({ key: f => f.path, observe: () => [...], enter: f => sh`...` })
   *   // then: <File path="x.txt" />
   */
  export function unit<T extends Record<string, unknown>>(
    def: UnitDef<T>
  ): (props: T) => EsNode;

  /** Template tag — runs a shell command at reconcile time. Interpolations are shell-quoted. */
  export declare const sh: (strings: TemplateStringsArray, ...values: unknown[]) => void;

  /** Template tag — emits an LLM task file for this leaf node. */
  export declare const prompt: (strings: TemplateStringsArray, ...values: unknown[]) => object;

  /** Returns true if path exists on disk. */
  export function exists(path: string): boolean;

  /** Reads path to a string. Throws if the file does not exist. */
  export function read(path: string): string;

  /** Lists filenames in dir. Returns [] if dir does not exist. */
  export function ls(dir: string): string[];

  /** Returns SHA-256 hex digest of input string. */
  export function hash(input: string): string;
}

declare module "esto/fs" {
  // ── Render-prop context shapes ────────────────────────────────────────────

  interface FileCtx {
    /** Path relative to the glob root or scope directory. */
    file: string;
  }

  interface FolderCtx {
    /** Path relative to the Folder's root. */
    dir: string;
    /** File component scoped to this directory. */
    File: typeof File;
    /** Folder component scoped to this directory. */
    Folder: typeof Folder;
  }

  interface RepoCtx {
    /** Absolute path to the git repository root. */
    repoRoot: string;
    /** File component scoped to the repo root. */
    File: typeof File;
    /** Folder component scoped to the repo root. */
    Folder: typeof Folder;
  }

  // ── File ─────────────────────────────────────────────────────────────────

  /** Enumerate mode: one render per matched file. */
  interface FileEnumerateProps {
    /** Glob pattern relative to the parent scope. */
    glob: string;
    /** Render prop called once per matched file. */
    children: (ctx: FileCtx) => unknown;
  }

  /** Supervisor claim mode (inside a Folder name="..."): declare membership. */
  interface FileClaimProps {
    /** Exact filename to claim. Creates the file if content is provided and it does not exist. */
    name?: string;
    /** Glob to claim a set of existing files. */
    glob?: string;
    /** Desired file content. If omitted, the file is kept at its current content. */
    content?: string;
    /** Optional render prop called with the resolved file path. */
    children?: (ctx: FileCtx) => unknown;
  }

  /**
   * Enumerate files or declare file claims inside a supervisor scope.
   *
   *   // Enumerate: <File glob="**\/*.ts">{({ file }) => <Seen file={file} />}</File>
   *   // Claim:     <File name="index.md" content={body} />
   */
  export function File(props: FileEnumerateProps | FileClaimProps): unknown;

  // ── Folder ────────────────────────────────────────────────────────────────

  /** Enumerate mode: one render per matched directory. */
  interface FolderEnumerateProps {
    /** Glob pattern matching directories. */
    glob: string;
    /** Render prop called once per matched directory. */
    children: (ctx: FolderCtx) => unknown;
  }

  /**
   * Supervisor mode: reconcile the named directory's file set declaratively.
   * File children are CLAIMS; unclaimed files are pruned (circuit-breaker guarded).
   */
  interface FolderSupervisorProps {
    /** Directory name relative to the parent scope. */
    name: string;
    /** Render prop receiving File + Folder for claim declarations. */
    children: (ctx: { File: typeof File; Folder: typeof Folder }) => unknown;
  }

  /**
   * Enumerate subdirectories or supervise a named directory's file set.
   *
   *   // Enumerate: <Folder glob="packages/*">{({ dir }) => ...}</Folder>
   *   // Supervisor: <Folder name="docs/api">{({ File }) => <File name="x.md" content={c} />}</Folder>
   */
  export function Folder(props: FolderEnumerateProps | FolderSupervisorProps): unknown;

  // ── GitRepo ───────────────────────────────────────────────────────────────

  /**
   * Resolves the git repository root and injects scoped File/Folder/repoRoot.
   *
   *   <GitRepo>{({ repoRoot, File, Folder }) => (
   *     <Folder glob="packages/*">{({ dir }) => ...}</Folder>
   *   )}</GitRepo>
   */
  export function GitRepo(props: {
    children: (ctx: RepoCtx) => unknown;
  }): unknown;
}
"#;
