use std::collections::HashMap;
use std::path::{Path, PathBuf};

use optative::{Lifecycle, OptativeJsonSet, OptativeSet, Reconcile};
use rquickjs::function::Function;
use rquickjs::loader::{BuiltinLoader, BuiltinResolver, Loader, Resolver};
use rquickjs::promise::MaybePromise;
use rquickjs::{Array, CaughtError, Context, Ctx, FromJs, Module, Object, Runtime, Value};

/// Turns a raw `rquickjs::Error` into a readable message: for a thrown JS `Error`
/// (the common case — a `sh` command failing, a userland `throw`), this pulls the
/// real `.message`/`.stack` off the exception instead of rquickjs's contentless
/// `Error::Exception` Display ("Exception generated by QuickJS"). Must be called
/// while `ctx` is still in scope — the exception state doesn't survive past it.
fn describe_js_error(ctx: &Ctx<'_>, err: rquickjs::Error) -> String {
    CaughtError::from_error(ctx, err).to_string()
}

/// First non-control-character Unicode code point (space, `U+0020`) — chars
/// below this need a `\uXXXX` escape in a JS string literal.
const ASCII_CONTROL_CHAR_LIMIT: u32 = 0x20;

/// Renders `s` as a JS double-quoted string literal. Used instead of Rust's
/// `{:?}` (`Debug`) escaping in `throw_type_error`, whose messages can embed
/// script-supplied paths or OS `io::Error` text: `Debug` escapes control
/// characters as `\u{7f}`-style braced hex, invalid JS syntax that would fail
/// `ctx.eval` and lose the real error message.
fn js_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < ASCII_CONTROL_CHAR_LIMIT => {
                out.push_str(&format!("\\u{:04x}", c as u32))
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Throws a JS `TypeError(msg)` and returns the resulting `rquickjs::Error` so
/// call sites can `return Err(throw_type_error(...))` inline.
fn throw_type_error<'js>(ctx: &Ctx<'js>, msg: &str) -> rquickjs::Error {
    let src = format!("new TypeError({})", js_string_literal(msg));
    let err = ctx
        .eval::<Value, _>(src)
        .unwrap_or_else(|_| Value::new_undefined(ctx.clone()));
    ctx.throw(err)
}
use sha2::{Digest, Sha256};

use crate::jsx::transform_source;
use crate::tags;

/// kind_id=0 is the synthetic bucket: non-JSX targets and leaves with a missing __estoId.
/// Real unit kinds are assigned ids starting at 1 by NEXT_KIND_ID in builtins/esto.rs.
const SYNTHETIC_KIND_ID: u32 = 0;

/// SHA-256 prefix length used as a short context identifier in task file names.
/// 12 hex chars give ~48 bits — low collision risk for typical context set sizes.
const CONTEXT_HASH_LEN: usize = 12;
/// Maximum number of characters taken from the first line of a context entry
/// for the human-readable reference comment in task files.
const CONTEXT_PREVIEW_LEN: usize = 60;

struct ScriptResolver {
    base_dir: PathBuf,
}

impl Resolver for ScriptResolver {
    fn resolve(&mut self, _ctx: &Ctx, base: &str, name: &str) -> rquickjs::Result<String> {
        if !name.starts_with("./") && !name.starts_with("../") {
            return Err(rquickjs::Error::new_resolving(base, name));
        }
        let dir = if Path::new(base).is_absolute() {
            Path::new(base)
                .parent()
                .map(|p| p.to_path_buf())
                .unwrap_or_else(|| self.base_dir.clone())
        } else {
            self.base_dir.clone()
        };
        dir.join(name)
            .canonicalize()
            .map_err(|_| rquickjs::Error::new_resolving(base, name))?
            .to_str()
            .map(|s| s.to_string())
            .ok_or_else(|| rquickjs::Error::new_resolving(base, name))
    }
}

struct ScriptLoader;

impl Loader for ScriptLoader {
    fn load<'js>(&mut self, ctx: &Ctx<'js>, name: &str) -> rquickjs::Result<Module<'js>> {
        let source =
            std::fs::read_to_string(name).map_err(|_| rquickjs::Error::new_loading(name))?;
        let source = if is_script_file(name) {
            transform_source(&source, name)
        } else {
            source
        };
        Module::declare(ctx.clone(), name, source)
    }
}

pub(crate) fn is_script_file(name: &str) -> bool {
    matches!(
        name.rsplit_once('.').map(|(_, e)| e),
        Some("jsx" | "tsx" | "ts" | "mts")
    )
}

pub fn serde_json_simple_array(items: &[String]) -> String {
    let inner: Vec<String> = items
        .iter()
        .map(|s| format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect();
    format!("[{}]", inner.join(","))
}

fn sha12(s: &str) -> String {
    let hash = Sha256::digest(s.as_bytes());
    format!("{hash:x}")[..CONTEXT_HASH_LEN].to_string()
}

fn emit_task(
    key: &str,
    context: &[String],
    context_data: &[String],
    body: &str,
) -> std::io::Result<()> {
    std::fs::create_dir_all("tasks")?;
    std::fs::create_dir_all(".esto/context")?;

    let refs: Vec<String> = context
        .iter()
        .map(|entry| {
            let hash = sha12(entry);
            let path = format!(".esto/context/{hash}.md");
            if !Path::new(&path).exists() {
                let _ = std::fs::write(&path, entry);
            }
            let first = entry
                .lines()
                .next()
                .unwrap_or("")
                .chars()
                .take(CONTEXT_PREVIEW_LEN)
                .collect::<String>();
            format!("  {path} — {first}")
        })
        .collect();

    let safe: String = key
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '.' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect();

    let mut sections: Vec<String> = Vec::new();
    if !refs.is_empty() {
        sections.push(format!(
            "Context (read once; same id = same content):\n{}",
            refs.join("\n")
        ));
    }
    if !context_data.is_empty() {
        let json = if context_data.len() == 1 {
            context_data[0].clone()
        } else {
            format!("[{}]", context_data.join(","))
        };
        sections.push(format!("Structured context:\n```json\n{json}\n```"));
    }

    let content = if sections.is_empty() {
        format!("# {key}\n{body}\n")
    } else {
        format!("# {key}\n{}\n\n{body}\n", sections.join("\n\n"))
    };

    std::fs::write(format!("tasks/{safe}.md"), content)
}

fn await_val<'js, T: FromJs<'js>>(val: Value<'js>) -> rquickjs::Result<T> {
    MaybePromise::from_value(val).finish()
}

fn check_prompt(
    key: &str,
    context: &[String],
    context_data: &[String],
    val: Value,
) -> rquickjs::Result<()> {
    if let Some(obj) = val.as_object()
        && let Ok(prompt_str) = obj.get::<_, String>("$prompt")
    {
        emit_task(key, context, context_data, &prompt_str).map_err(rquickjs::Error::Io)?;
    }
    Ok(())
}

struct Leaf<'js> {
    kind_id: u32,
    kind: Object<'js>,
    item: Value<'js>,
    context: Vec<String>,
    context_data: Vec<String>,
}

/// Pushes `props.value`/`props.data` onto the ambient context stacks the
/// same way `h_fn` used to when it had a dedicated Context branch — except
/// `data` now arrives as a live JS value (not pre-stringified), since
/// `h_fn`'s generic passthrough case doesn't know a node is a `Context` node.
/// So the `JSON.stringify` that used to happen in `h_fn` happens here instead.
fn accumulate_context<'js>(
    ctx: &Ctx<'js>,
    props: &Object<'js>,
    context: &[String],
    context_data: &[String],
) -> rquickjs::Result<(Vec<String>, Vec<String>)> {
    let mut new_ctx = context.to_vec();
    let v: Value = props.get("value")?;
    if let Some(s) = v.as_string() {
        new_ctx.push(s.to_string()?);
    }

    let mut new_ctx_data = context_data.to_vec();
    let d: Value = props.get("data")?;
    if !d.is_null() && !d.is_undefined() {
        new_ctx_data.push(crate::runtime::json_stringify(ctx, d)?);
    }

    Ok((new_ctx, new_ctx_data))
}

/// Walks an already-fully-eagerly-materialized JSX tree (every component in
/// it has already been called by `h_fn`) collecting `Leaf`s for
/// reconciliation. There's no `is_fragment`/`is_component` case anymore:
/// Fragment output is a plain array (handled by the `is_array` branch below)
/// and every component has already been resolved to its actual output by the
/// time `h_fn` returns. `Context` and `unit()`-produced kind descriptors are
/// recognized structurally from a passthrough node's `type` field.
fn reduce<'js>(
    ctx: &Ctx<'js>,
    node: Value<'js>,
    context: Vec<String>,
    context_data: Vec<String>,
) -> rquickjs::Result<Vec<Leaf<'js>>> {
    if node.is_null() || node.is_undefined() {
        return Ok(vec![]);
    }
    if let Some(false) = node.as_bool() {
        return Ok(vec![]);
    }
    if let Some(arr) = node.as_array() {
        let mut leaves = vec![];
        for i in 0..arr.len() {
            let child: Value = arr.get(i)?;
            leaves.extend(reduce(ctx, child, context.clone(), context_data.clone())?);
        }
        return Ok(leaves);
    }
    if let Some(obj) = node.as_object() {
        let type_val: Value = obj.get("type")?;
        if let Some(type_obj) = type_val.as_object() {
            if type_obj.contains_key(tags::ESTO_CONTEXT)? {
                let props: Object = obj.get("props")?;
                let (new_ctx, new_ctx_data) =
                    accumulate_context(ctx, &props, &context, &context_data)?;
                let children: Array = obj.get("children")?;
                let mut leaves = vec![];
                for i in 0..children.len() {
                    let child: Value = children.get(i)?;
                    leaves.extend(reduce(ctx, child, new_ctx.clone(), new_ctx_data.clone())?);
                }
                return Ok(leaves);
            }
            if type_obj.contains_key(tags::ESTO_KIND)? {
                let kind_id: u32 = type_obj.get(tags::ESTO_ID).unwrap_or(SYNTHETIC_KIND_ID);
                let item: Value = obj.get("props")?;
                return Ok(vec![Leaf {
                    kind_id,
                    kind: type_obj.clone(),
                    item,
                    context,
                    context_data,
                }]);
            }
        }
    }
    {
        let err = ctx
            .eval::<Value, _>(r#"new TypeError("esto: reduce encountered an unknown node type")"#)
            .unwrap_or_else(|_| Value::new_undefined(ctx.clone()));
        Err(ctx.throw(err))
    }
}

pub struct RunStats {
    pub enter: usize,
    pub update: usize,
    pub exit: usize,
    pub unchanged: usize,
    pub errors: usize,
    /// Items that would have entered/updated/exited but were skipped because
    /// `--limit` was already reached. Tracked separately from `unchanged` so a
    /// limited run is never mistaken for a converged one.
    pub limited: usize,
}

fn call_and_check<'js>(
    func: Function<'js>,
    args: Vec<Value<'js>>,
    key: &str,
    context: &[String],
    context_data: &[String],
) -> rquickjs::Result<()> {
    let raw: Value = match args.len() {
        0 => func.call::<(), Value>(()),
        1 => func.call::<(Value,), Value>((args[0].clone(),)),
        2 => func.call::<(Value, Value), Value>((args[0].clone(), args[1].clone())),
        _ => return Ok(()),
    }?;
    let resolved: Value = await_val(raw)?;
    check_prompt(key, context, context_data, resolved)
}

/// Per-item state `optative::OptativeSet` remembers between `enter`/`reconcile_self`/
/// `exit` — the previous item's live JS handle (passed as the "old" argument to
/// `update`/`exit`) plus its value string (for change detection) and key (`exit` only
/// receives `State`, not the original `JsLeaf`, so the key has to travel with it).
struct JsLeafState<'js> {
    key: String,
    item: Value<'js>,
    value_str: String,
}

/// One JSX-tree leaf, converted into an `optative::Lifecycle` item. `key()`/`enter()`/
/// `reconcile_self()`/`exit()` dispatch to the JS unit's own functions of the same
/// name — this is the same dispatch `call_lifecycle` used to do by hand, now expressed
/// as the trait `optative::OptativeSet::reconcile()` already knows how to drive.
struct JsLeaf<'js> {
    key: String,
    value_str: String,
    item: Value<'js>,
    context: Vec<String>,
    context_data: Vec<String>,
}

/// Per-item state for `optativeJsonSet`-backed units, persisted to a jsonl file
/// across separate `esto` runs. Unlike `JsLeafState`, it can't hold a live
/// `rquickjs::Value` (no JS heap survives between runs) — the item is kept as
/// JSON text and reconstructed via `JSON.parse` when a hook needs the "old"
/// value (`update`'s second argument, `exit`'s argument).
#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct JsonLeafState {
    key: String,
    item_json: String,
    value_str: String,
}

/// `JsLeaf` wrapped for the `optativeJsonSet` backend (see `JsonLeafState`) — a
/// newtype rather than a generic param because a type can only implement
/// `Lifecycle` once, and `JsLeaf` already implements it for `optativeSet`.
struct JsLeafJson<'js>(JsLeaf<'js>);

/// Shared, mutable state threaded through every `enter`/`reconcile_self`/`exit` call
/// in one `reconcile()` pass: the JS `Ctx`/Kind object every dispatch needs, the
/// dry-run/quiet flags, and running counts `reconcile_kind` reads back afterward
/// (`optative::Reconcile::reconcile` returns the error list, but not per-category
/// enter/update/exit/unchanged counts, so those are accumulated here — same role
/// `WorkerPools` played for the now-removed shell-tier `HookItem`).
struct ReconcileCtx<'js> {
    js_ctx: Ctx<'js>,
    kind: Object<'js>,
    dry_run: bool,
    quiet: bool,
    /// Caps total enter+update+exit dispatches for THIS Kind (`--limit`). Scope
    /// boundary, not yet solved: a script with multiple `unit()` Kinds gets this
    /// budget separately per Kind, not shared across the whole run — deliberately
    /// deferred until something actually needs it.
    limit: Option<usize>,
    dispatched: usize,
    enter_count: usize,
    update_count: usize,
    exit_count: usize,
    unchanged_count: usize,
    limited_count: usize,
}

impl<'js> ReconcileCtx<'js> {
    /// True if this item's dispatch should be skipped because `--limit` is
    /// already spent. Selection isn't based on any deliberate ordering — the
    /// item stream here comes from a plain HashMap inside `optative`, whose
    /// iteration order isn't stable across runs (or even across processes,
    /// given Rust's randomized hash seed). Which N items get processed under
    /// `--limit N` is arbitrary, not "the first N" in any meaningful sense.
    fn over_limit(&mut self) -> bool {
        match self.limit {
            Some(n) if self.dispatched >= n => {
                self.limited_count += 1;
                true
            }
            _ => {
                self.dispatched += 1;
                false
            }
        }
    }
}

/// Calls `rc.kind[method]` (if present and callable) with `args`, unless dry-run.
/// Missing/non-function hooks are a silent no-op — a unit() doesn't have to define
/// every lifecycle method.
fn dispatch_hook<'js>(
    rc: &ReconcileCtx<'js>,
    method: &str,
    args: Vec<Value<'js>>,
    key: &str,
    context: &[String],
    context_data: &[String],
) -> Result<(), String> {
    if rc.dry_run {
        return Ok(());
    }
    let fn_val: Value = match rc.kind.get(method) {
        Ok(v) => v,
        Err(_) => return Ok(()),
    };
    if !fn_val.is_function() {
        return Ok(());
    }
    let func = match fn_val.into_function() {
        Some(f) => f,
        None => return Ok(()),
    };
    call_and_check(func, args, key, context, context_data)
        .map_err(|e| describe_js_error(&rc.js_ctx, e))
}

/// The part of enter/update/exit shared by every `Lifecycle` impl in this file,
/// once the caller has already decided (via `rc.over_limit()`) that the hook
/// should actually fire: log `[method] key` (unless quiet), bump the matching
/// counter, and dispatch. `method` is always one of "enter"/"update"/"exit".
fn log_count_and_dispatch<'js>(
    rc: &mut ReconcileCtx<'js>,
    method: &str,
    key: &str,
    args: Vec<Value<'js>>,
    context: &[String],
    context_data: &[String],
) -> Result<(), String> {
    if !rc.quiet {
        eprintln!("[{method}] {key}");
    }
    match method {
        "enter" => rc.enter_count += 1,
        "update" => rc.update_count += 1,
        "exit" => rc.exit_count += 1,
        _ => {}
    }
    dispatch_hook(rc, method, args, key, context, context_data)
}

impl<'js> JsLeaf<'js> {
    fn into_state(self) -> JsLeafState<'js> {
        JsLeafState {
            key: self.key,
            item: self.item,
            value_str: self.value_str,
        }
    }
}

impl<'js> Lifecycle for JsLeaf<'js> {
    type Key = String;
    type State = JsLeafState<'js>;
    type Context = ReconcileCtx<'js>;
    type Output = ();
    type Error = String;

    fn key(&self) -> String {
        self.key.clone()
    }

    fn enter(
        self,
        rc: &mut ReconcileCtx<'js>,
        _output: &mut (),
    ) -> Result<JsLeafState<'js>, String> {
        if rc.over_limit() {
            return Ok(self.into_state());
        }
        log_count_and_dispatch(
            rc,
            "enter",
            &self.key,
            vec![self.item.clone()],
            &self.context,
            &self.context_data,
        )?;
        Ok(self.into_state())
    }

    fn reconcile_self(
        self,
        state: &mut JsLeafState<'js>,
        rc: &mut ReconcileCtx<'js>,
        _output: &mut (),
    ) -> Result<(), String> {
        if self.value_str == state.value_str {
            rc.unchanged_count += 1;
            return Ok(());
        }
        if rc.over_limit() {
            return Ok(());
        }
        log_count_and_dispatch(
            rc,
            "update",
            &self.key,
            vec![self.item.clone(), state.item.clone()],
            &self.context,
            &self.context_data,
        )?;
        state.item = self.item;
        state.value_str = self.value_str;
        Ok(())
    }

    fn exit(
        state: JsLeafState<'js>,
        rc: &mut ReconcileCtx<'js>,
        _output: &mut (),
    ) -> Result<(), String> {
        if rc.over_limit() {
            return Ok(());
        }
        log_count_and_dispatch(rc, "exit", &state.key, vec![state.item.clone()], &[], &[])?;
        Ok(())
    }
}

impl<'js> JsLeafJson<'js> {
    fn into_state(self, rc: &ReconcileCtx<'js>) -> Result<JsonLeafState, String> {
        let item_json = crate::runtime::json_stringify(&rc.js_ctx, self.0.item)
            .map_err(|e| describe_js_error(&rc.js_ctx, e))?;
        Ok(JsonLeafState {
            key: self.0.key,
            item_json,
            value_str: self.0.value_str,
        })
    }
}

/// Same enter/reconcile_self/exit dispatch as `Lifecycle for JsLeaf`, except the
/// "old" item handed to `update`/`exit` is reconstructed via `JSON.parse` from
/// `JsonLeafState::item_json` rather than carried as a live `Value` — see
/// `JsonLeafState`.
impl<'js> Lifecycle for JsLeafJson<'js> {
    type Key = String;
    type State = JsonLeafState;
    type Context = ReconcileCtx<'js>;
    type Output = ();
    type Error = String;

    fn key(&self) -> String {
        self.0.key.clone()
    }

    fn enter(self, rc: &mut ReconcileCtx<'js>, _output: &mut ()) -> Result<JsonLeafState, String> {
        if rc.over_limit() {
            return self.into_state(rc);
        }
        log_count_and_dispatch(
            rc,
            "enter",
            &self.0.key,
            vec![self.0.item.clone()],
            &self.0.context,
            &self.0.context_data,
        )?;
        self.into_state(rc)
    }

    fn reconcile_self(
        self,
        state: &mut JsonLeafState,
        rc: &mut ReconcileCtx<'js>,
        _output: &mut (),
    ) -> Result<(), String> {
        if self.0.value_str == state.value_str {
            rc.unchanged_count += 1;
            return Ok(());
        }
        if rc.over_limit() {
            return Ok(());
        }
        let old_item = crate::runtime::json_parse(&rc.js_ctx, &state.item_json)
            .map_err(|e| describe_js_error(&rc.js_ctx, e))?;
        log_count_and_dispatch(
            rc,
            "update",
            &self.0.key,
            vec![self.0.item.clone(), old_item],
            &self.0.context,
            &self.0.context_data,
        )?;
        state.item_json = crate::runtime::json_stringify(&rc.js_ctx, self.0.item)
            .map_err(|e| describe_js_error(&rc.js_ctx, e))?;
        state.value_str = self.0.value_str;
        Ok(())
    }

    fn exit(
        state: JsonLeafState,
        rc: &mut ReconcileCtx<'js>,
        _output: &mut (),
    ) -> Result<(), String> {
        if rc.over_limit() {
            return Ok(());
        }
        let old_item = crate::runtime::json_parse(&rc.js_ctx, &state.item_json)
            .map_err(|e| describe_js_error(&rc.js_ctx, e))?;
        log_count_and_dispatch(rc, "exit", &state.key, vec![old_item], &[], &[])?;
        Ok(())
    }
}

fn new_reconcile_ctx<'js>(
    ctx: &Ctx<'js>,
    kind: &Object<'js>,
    dry_run: bool,
    quiet: bool,
    limit: Option<usize>,
) -> ReconcileCtx<'js> {
    ReconcileCtx {
        js_ctx: ctx.clone(),
        kind: kind.clone(),
        dry_run,
        quiet,
        limit,
        dispatched: 0,
        enter_count: 0,
        update_count: 0,
        exit_count: 0,
        unchanged_count: 0,
        limited_count: 0,
    }
}

fn run_stats_from(
    rc: &ReconcileCtx,
    errors: &optative::ReconcileErrors<String, String>,
) -> RunStats {
    for (key, msg) in errors {
        eprintln!("[error] {key}: {msg}");
    }
    RunStats {
        enter: rc.enter_count,
        update: rc.update_count,
        exit: rc.exit_count,
        unchanged: rc.unchanged_count,
        errors: errors.len(),
        limited: rc.limited_count,
    }
}

/// Which `optative::Reconcile` backend tracks a Kind's state between runs — a
/// runtime choice (JS's dynamism means "which reconciler did this script pick"
/// is only knowable at this point, not at compile time), read off the
/// `optativeSet(...)`/`optativeJsonSet(...)`-tagged `reconciler` descriptor.
enum ReconcilerBackend {
    OptativeSet,
    OptativeJsonSet,
}

impl ReconcilerBackend {
    fn from_tag(ctx: &Ctx<'_>, tag: &str) -> rquickjs::Result<Self> {
        match tag {
            "optativeSet" => Ok(Self::OptativeSet),
            "optativeJsonSet" => Ok(Self::OptativeJsonSet),
            other => Err(throw_type_error(
                ctx,
                &format!("esto: unknown reconciler kind {other:?}"),
            )),
        }
    }
}

/// Reads and validates `kind.reconciler`, returning the descriptor object and
/// which backend it names.
fn reconciler_backend<'js>(
    ctx: &Ctx<'js>,
    kind: &Object<'js>,
) -> rquickjs::Result<(Object<'js>, ReconcilerBackend)> {
    let reconciler_val: Value = kind.get("reconciler")?;
    let reconciler: Object = reconciler_val.as_object().cloned().ok_or_else(|| {
        throw_type_error(
            ctx,
            "esto: unit() requires `reconciler: optativeSet({ observe }) | optativeJsonSet({ file })`",
        )
    })?;
    let tag: String = reconciler.get(tags::ESTO_RECONCILER_KIND).map_err(|_| {
        throw_type_error(
            ctx,
            "esto: `reconciler` must be built with optativeSet(...) or optativeJsonSet(...)",
        )
    })?;
    let backend = ReconcilerBackend::from_tag(ctx, &tag)?;
    Ok((reconciler, backend))
}

fn build_desired<'js>(
    leaves: Vec<Leaf<'js>>,
    key_fn: &Function<'js>,
    value_fn: &Function<'js>,
) -> rquickjs::Result<Vec<JsLeaf<'js>>> {
    let mut desired = Vec::new();
    for leaf in leaves {
        let k: String = key_fn.call::<(Value,), String>((leaf.item.clone(),))?;
        let v: String = value_fn.call::<(Value,), String>((leaf.item.clone(),))?;
        desired.push(JsLeaf {
            key: k,
            value_str: v,
            item: leaf.item,
            context: leaf.context,
            context_data: leaf.context_data,
        });
    }
    Ok(desired)
}

/// In-memory backend: state is reseeded from `reconciler.observe()` every run.
fn reconcile_via_optative_set<'js>(
    ctx: &Ctx<'js>,
    reconciler: &Object<'js>,
    key_fn: &Function<'js>,
    value_fn: &Function<'js>,
    desired: Vec<JsLeaf<'js>>,
    rc: &mut ReconcileCtx<'js>,
) -> rquickjs::Result<RunStats> {
    let observe_fn: Function = reconciler.get("observe")?;
    let obs_raw: Value = observe_fn.call::<(), Value>(())?;
    let obs_val: Value = await_val(obs_raw)?;
    let obs_arr = obs_val
        .into_array()
        .ok_or_else(|| throw_type_error(ctx, "esto: observe() must return an array"))?;

    let mut initial: Vec<(String, JsLeafState<'js>)> = Vec::new();
    for i in 0..obs_arr.len() {
        let item: Value = obs_arr.get(i)?;
        let k: String = key_fn.call::<(Value,), String>((item.clone(),))?;
        let v: String = value_fn.call::<(Value,), String>((item.clone(),))?;
        initial.push((
            k.clone(),
            JsLeafState {
                key: k,
                item,
                value_str: v,
            },
        ));
    }

    let mut set: OptativeSet<JsLeaf<'js>> = OptativeSet::with_initial_state(initial);
    let errors = set.reconcile(desired, rc, &mut ());
    Ok(run_stats_from(rc, &errors))
}

/// Jsonl-file-persisted backend: state survives across separate `esto`
/// processes, seeded from `reconciler.file` with no `observe()` needed.
fn reconcile_via_optative_json_set<'js>(
    ctx: &Ctx<'js>,
    reconciler: &Object<'js>,
    desired: Vec<JsLeaf<'js>>,
    dry_run: bool,
    rc: &mut ReconcileCtx<'js>,
) -> rquickjs::Result<RunStats> {
    let file: String = reconciler.get("file")?;
    let mut json_set: OptativeJsonSet<JsLeafJson<'js>> =
        OptativeJsonSet::open(&file).map_err(|e| {
            throw_type_error(
                ctx,
                &format!("esto: failed to open reconciler state file {file:?}: {e}"),
            )
        })?;
    let desired: Vec<JsLeafJson<'js>> = desired.into_iter().map(JsLeafJson).collect();

    // OptativeJsonSet::reconcile always persists — never invoke it in dry-run.
    // Re-diff the same loaded entries through a throwaway in-memory OptativeSet
    // instead, so dry-run never persists reconciled state to the file
    // (OptativeJsonSet::open above may still delete a stale `<file>.new.<pid>`
    // crash leftover — harmless crash-artifact cleanup, not state).
    let (errors, persist_error) = if dry_run {
        let initial: Vec<(String, JsonLeafState)> = json_set
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        let mut set = OptativeSet::with_initial_state(initial);
        (set.reconcile(desired, rc, &mut ()), None)
    } else {
        let errors = json_set.reconcile(desired, rc, &mut ());
        (errors, json_set.persist_error().map(|e| e.to_string()))
    };

    let mut stats = run_stats_from(rc, &errors);
    if let Some(msg) = persist_error {
        eprintln!("[error] failed to persist reconciler state to {file}: {msg}");
        stats.errors += 1;
    }
    Ok(stats)
}

/// Diffs `leaves` (the desired set) against this Kind's tracked state and
/// drives enter/update/exit for the delta, via whichever `optative::Reconcile`
/// backend `kind.reconciler` names.
#[allow(clippy::too_many_arguments)]
fn reconcile_kind<'js>(
    ctx: &Ctx<'js>,
    kind: &Object<'js>,
    leaves: Vec<Leaf<'js>>,
    dry_run: bool,
    quiet: bool,
    limit: Option<usize>,
) -> rquickjs::Result<RunStats> {
    let key_fn: Function = kind.get("key")?;
    let value_fn: Function = kind.get("value")?;
    let (reconciler, backend) = reconciler_backend(ctx, kind)?;
    let desired = build_desired(leaves, &key_fn, &value_fn)?;
    let mut rc = new_reconcile_ctx(ctx, kind, dry_run, quiet, limit);

    match backend {
        ReconcilerBackend::OptativeSet => {
            reconcile_via_optative_set(ctx, &reconciler, &key_fn, &value_fn, desired, &mut rc)
        }
        ReconcilerBackend::OptativeJsonSet => {
            reconcile_via_optative_json_set(ctx, &reconciler, desired, dry_run, &mut rc)
        }
    }
}

/// Builds a fresh `Runtime`/`Context` pair, wiring up the synthetic builtin
/// modules derived from `entries` alongside a caller-supplied `resolver`/
/// `loader` pair for everything else (typically `./`/`../` relative
/// filesystem imports).
///
/// Public so a caller that needs the raw `Runtime`/`Context` for its own
/// evaluation loop (e.g. a persistent, re-invoked-many-times evaluator, as
/// opposed to esto's one-shot [`run_script`]/[`run_script_with_loader`]) can
/// reuse this wiring instead of re-implementing the `EsEntry` grouping and
/// `BuiltinResolver`/`BuiltinLoader` fold by hand.
pub fn build_runtime<R, L>(
    entries: &[crate::EsEntry],
    resolver: R,
    loader: L,
) -> rquickjs::Result<(Runtime, Context)>
where
    R: Resolver + 'static,
    L: Loader + 'static,
{
    let runtime = Runtime::new()?;
    let mut module_groups: HashMap<&'static str, Vec<&crate::EsEntry>> = HashMap::new();
    for e in entries {
        module_groups.entry(e.module_path).or_default().push(e);
    }
    let builtin_resolver = module_groups
        .keys()
        .fold(BuiltinResolver::default(), |r, path| r.with_module(*path));
    let builtin_loader = module_groups
        .iter()
        .fold(BuiltinLoader::default(), |l, (path, es)| {
            l.with_module(*path, crate::synthetic_module_source_for_entries(es))
        });
    runtime.set_loader((builtin_resolver, resolver), (builtin_loader, loader));
    let context = Context::full(&runtime)?;
    Ok((runtime, context))
}

fn collect_leaves<'js>(
    ctx: &Ctx<'js>,
    path_str: &str,
    src: &str,
    is_jsx: bool,
) -> rquickjs::Result<Vec<Leaf<'js>>> {
    let module = Module::declare(ctx.clone(), path_str.to_string(), src.to_string())?;
    let (module, promise) = module.eval()?;
    promise.finish::<()>()?;

    let default_val: Value = module.get("default")?;

    let leaves = if is_jsx {
        let root_fn = default_val.into_function().ok_or_else(|| {
            let err = ctx
                .eval::<Value, _>(
                    r#"new TypeError("esto: JSX script default export must be a function")"#,
                )
                .unwrap_or_else(|_| Value::new_undefined(ctx.clone()));
            ctx.throw(err)
        })?;
        let root: Value = root_fn.call::<(), Value>(())?;
        reduce(ctx, root, vec![], vec![])?
    } else {
        let target = default_val.into_object().ok_or_else(|| {
            let err = ctx
                .eval::<Value, _>(
                    r#"new TypeError("esto: non-JSX script default export must be an object")"#,
                )
                .unwrap_or_else(|_| Value::new_undefined(ctx.clone()));
            ctx.throw(err)
        })?;
        let desired_fn: Function = target.get("desired")?;
        let desired_raw: Value = desired_fn.call::<(), Value>(())?;
        let desired_val: Value = await_val(desired_raw)?;
        let desired_arr = desired_val.into_array().ok_or_else(|| {
            let err = ctx
                .eval::<Value, _>(r#"new TypeError("esto: desired() must return an array")"#)
                .unwrap_or_else(|_| Value::new_undefined(ctx.clone()));
            ctx.throw(err)
        })?;
        let mut leaves = Vec::new();
        for i in 0..desired_arr.len() {
            let item: Value = desired_arr.get(i)?;
            leaves.push(Leaf {
                kind_id: SYNTHETIC_KIND_ID,
                kind: target.clone(),
                item,
                context: vec![],
                context_data: vec![],
            });
        }
        leaves
    };

    Ok(leaves)
}

/// Runs `path` with the default filesystem resolver/loader: relative imports
/// resolve against the script's own directory with no path confinement and
/// no extension-fallback (the import specifier must match the target
/// filename exactly). This is esto's existing behavior, unchanged.
#[allow(clippy::too_many_arguments)]
pub fn run_script(
    path: &str,
    entries: &[crate::EsEntry],
    setup: fn(&Ctx<'_>) -> rquickjs::Result<()>,
    dry_run: bool,
    quiet: bool,
    limit: Option<usize>,
) -> Result<RunStats, crate::ScriptError> {
    let abs_path = std::path::Path::new(path)
        .canonicalize()
        .map_err(crate::ScriptError::Io)?;
    let base_dir = abs_path
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_default();
    run_script_with_loader(
        path,
        entries,
        setup,
        dry_run,
        quiet,
        limit,
        ScriptResolver { base_dir },
        ScriptLoader,
    )
}

/// Like [`run_script`], but with a caller-supplied resolver/loader pair
/// instead of the default [`ScriptResolver`]/[`ScriptLoader`]. Use this to
/// opt into a different import-resolution policy — for example
/// [`crate::loader::ConfinedFsResolver`]/[`crate::loader::ConfinedFsLoader`]
/// for path-confined, extension-fallback resolution.
#[allow(clippy::too_many_arguments)]
pub fn run_script_with_loader<R, L>(
    path: &str,
    entries: &[crate::EsEntry],
    setup: fn(&Ctx<'_>) -> rquickjs::Result<()>,
    dry_run: bool,
    quiet: bool,
    limit: Option<usize>,
    resolver: R,
    loader: L,
) -> Result<RunStats, crate::ScriptError>
where
    R: Resolver + 'static,
    L: Loader + 'static,
{
    let abs_path = std::path::Path::new(path)
        .canonicalize()
        .map_err(crate::ScriptError::Io)?;
    let path_str = abs_path
        .to_str()
        .ok_or_else(|| crate::ScriptError::InvalidPath(abs_path.to_string_lossy().into_owned()))?
        .to_string();
    let needs_transform = is_script_file(&path_str);
    let is_jsx = path_str.ends_with(".jsx") || path_str.ends_with(".tsx");

    let src_raw = std::fs::read_to_string(&path_str).map_err(crate::ScriptError::Io)?;
    let src = if needs_transform {
        transform_source(&src_raw, &path_str)
    } else {
        src_raw
    };

    eval_and_reconcile(
        &path_str, &src, is_jsx, entries, setup, dry_run, quiet, limit, resolver, loader,
    )
}

/// Like [`run_script_with_loader`], but takes a pre-supplied `source` instead
/// of reading and transforming `path` from disk — `source` is used verbatim,
/// with no further transformation. `path` is still canonicalized and used for
/// `base_dir` (relative-import resolution), diagnostics, and as the
/// evaluated module's registered name.
///
/// `is_jsx` selects the default export's expected shape (a JSX-tree-
/// returning function vs. a `desired()`-returning object) — the same
/// distinction [`run_script_with_loader`] infers from `path`'s extension for
/// `.jsx`/`.tsx` files, made explicit here since `path`'s extension may not
/// reflect `source`'s actual shape (e.g. a source lowered from a non-JS
/// input format).
#[allow(clippy::too_many_arguments)]
pub fn run_script_with_source_and_loader<R, L>(
    path: &str,
    source: &str,
    is_jsx: bool,
    entries: &[crate::EsEntry],
    setup: fn(&Ctx<'_>) -> rquickjs::Result<()>,
    dry_run: bool,
    quiet: bool,
    limit: Option<usize>,
    resolver: R,
    loader: L,
) -> Result<RunStats, crate::ScriptError>
where
    R: Resolver + 'static,
    L: Loader + 'static,
{
    let abs_path = std::path::Path::new(path)
        .canonicalize()
        .map_err(crate::ScriptError::Io)?;
    let path_str = abs_path
        .to_str()
        .ok_or_else(|| crate::ScriptError::InvalidPath(abs_path.to_string_lossy().into_owned()))?
        .to_string();

    eval_and_reconcile(
        &path_str, source, is_jsx, entries, setup, dry_run, quiet, limit, resolver, loader,
    )
}

/// Like [`run_script`], but takes a pre-supplied `source` — see
/// [`run_script_with_source_and_loader`] for details. Uses the default
/// filesystem resolver/loader, same as [`run_script`].
#[allow(clippy::too_many_arguments)]
pub fn run_script_with_source(
    path: &str,
    source: &str,
    is_jsx: bool,
    entries: &[crate::EsEntry],
    setup: fn(&Ctx<'_>) -> rquickjs::Result<()>,
    dry_run: bool,
    quiet: bool,
    limit: Option<usize>,
) -> Result<RunStats, crate::ScriptError> {
    let abs_path = std::path::Path::new(path)
        .canonicalize()
        .map_err(crate::ScriptError::Io)?;
    let base_dir = abs_path
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_default();
    run_script_with_source_and_loader(
        path,
        source,
        is_jsx,
        entries,
        setup,
        dry_run,
        quiet,
        limit,
        ScriptResolver { base_dir },
        ScriptLoader,
    )
}

#[allow(clippy::too_many_arguments)]
fn eval_and_reconcile<R, L>(
    path_str: &str,
    src: &str,
    is_jsx: bool,
    entries: &[crate::EsEntry],
    setup: fn(&Ctx<'_>) -> rquickjs::Result<()>,
    dry_run: bool,
    quiet: bool,
    limit: Option<usize>,
    resolver: R,
    loader: L,
) -> Result<RunStats, crate::ScriptError>
where
    R: Resolver + 'static,
    L: Loader + 'static,
{
    if limit.is_some() && !quiet {
        eprintln!(
            "esto run: --limit is set — which items get selected is not stable across runs \
             (item order comes from an unordered internal HashMap); re-running may pick a \
             different subset."
        );
    }

    let (_runtime, context) = build_runtime(entries, resolver, loader)
        .map_err(|e| crate::ScriptError::Worker(e.to_string()))?;

    let stats = context
        .with(|ctx| -> Result<RunStats, String> {
            let result: rquickjs::Result<RunStats> = (|| {
                setup(&ctx)?;

                let leaves = collect_leaves(&ctx, path_str, src, is_jsx)?;

                let mut by_kind: HashMap<u32, (Object, Vec<Leaf>)> = HashMap::new();
                for leaf in leaves {
                    let entry = by_kind
                        .entry(leaf.kind_id)
                        .or_insert_with(|| (leaf.kind.clone(), vec![]));
                    entry.1.push(leaf);
                }

                let mut stats = RunStats {
                    enter: 0,
                    update: 0,
                    exit: 0,
                    unchanged: 0,
                    errors: 0,
                    limited: 0,
                };

                for (_, (kind_obj, kind_leaves)) in by_kind {
                    let res = reconcile_kind(&ctx, &kind_obj, kind_leaves, dry_run, quiet, limit)?;
                    stats.enter += res.enter;
                    stats.update += res.update;
                    stats.exit += res.exit;
                    stats.unchanged += res.unchanged;
                    stats.errors += res.errors;
                    stats.limited += res.limited;
                }

                Ok(stats)
            })();
            // Unwrap the real JS exception (message + stack) while `ctx` is still
            // alive — once this closure returns, the exception state is gone and
            // all that's left is rquickjs's contentless `Error::Exception` Display.
            result.map_err(|e| describe_js_error(&ctx, e))
        })
        .map_err(crate::ScriptError::Worker)?;

    if !quiet {
        let limited_note = if stats.limited > 0 {
            format!(", {} limited", stats.limited)
        } else {
            String::new()
        };
        eprintln!(
            "reconciled: {} enter, {} update, {} exit ({} unchanged{limited_note})",
            stats.enter, stats.update, stats.exit, stats.unchanged
        );
    }

    Ok(stats)
}
